### ISSUE TITLE
installation failed: syntax error in generated configure script

### ISSUE THREAD

**Issue by jdkloe** [stcorp/harp#1]
As explained in issue #1 on the related coda package, the autotools must be applied before the software can be installed. It would be good to add this to the INSTALL file.
However, the configure file generated this way does not work for me.
I issued these commands:
```
ln -s ./config.h.cmake.in config.h.in
libtoolize
aclocal
autoconf
automake -a

./configure --prefix=`pwd`/../harp_install
```
but the configure stage fails with this error:
```
 >./configure --prefix=`pwd`/../harp_install
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 3288: syntax error near unexpected token `$srcdir/definitions,ENVISAT_GOMOS'
./configure: line 3288: `ST_CODADEF_VERSION($srcdir/definitions,ENVISAT_GOMOS)'
```

**Comment by svniemeijer** [comment]
Please use the bootstrap script. Copying config.h.cmake.in to config.h.in is not going to work.

**Comment by jdkloe** [comment]
I did a fresh git clone and used the bootstrap script this time, but still get the same error when I run the ./configure script.  There must be some additional problem I think.

**Comment by svniemeijer** [comment]
Did you initialize and fetch all git submodules?

**Comment by jdkloe** [comment]
No, I was not aware the project used git submodules. There is no mention of it in the README or INSTALL files.
Yes, this solves the configure issue for me. Just for future reference, I issued these commands to clone the project:
```
git clone https://github.com/stcorp/harp.git
cd coda
git submodule init
git submodule update
```

**Comment by svniemeijer** [comment]
I assume you mean 'cd harp', since you don't have to be inside a submodule directory to init/update it.
And note that all codadefs are also submodules.

And we will add these instructions to the README/INSTALL. But for now we want users to use the official source package.

**Comment by svniemeijer** [comment]
Instructions for building directly from a github clone have been added to the documentation
