### ISSUE TITLE
Javascript files are not copied on compile

### ISSUE THREAD

**Issue by mobinni** [stcorp/harp#104]
I have an odd error:

When I run harp server, everything runs perfectly, however when I run harp compile not all files referenced als links or scripts are copied to the www/ folder. It seems to be that it compiles the css correctly from the styles folder, but JS files and css files from other folders are not copied.

Any idea why this would happen?

Configuration:
- harp 0.23
- node 6.0.0

**Comment by svniemeijer** [comment]
I think you have posted this issue in the wrong place. This HARP software is not a javascript codebase. I think you meant https://github.com/harp. Please post the issue there.

**Comment by mobinni** [comment]
Oops my bad!
