### ISSUE TITLE
Check/update vertical smoothing outside vertical bounds

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#107]
If we smooth a vertical profile with a 2D averaging kernel where the avering kernel has a larger vertical extent than the to-be-smoothed profile then make sure that the extended parts end up becoming equal to the apriori (as associated with the AVK).

This may already be the case in the implementation, but this needs to be checked.

The main thing is that we don't want the extended parts to become NaN and then have the smoothed profile turned into NaN values.

**Comment by StevenCompernolle** [comment]
Extending the to-be-smoothed profile (profile B) with the a priori of profile A should result in a smoothed profile where no information from the extended part is introduced. 
Take range 1 the core part, and range 2 the extended part, one has in the smoothing equation, for the core part, in general

xrefsm_1 = (A_11 A_12) (xref_1 xref_2) + (I -A_11) xa_1 - A_12 xa_2 

If now xref_2 = xa_2 (i.e., extending a too short ref profile with the satellite a priori), there is a cancellation of terms and one gets

xrefsm_1 = A_11 xref_1 + (I -A_11) xa_1

Extending with the a priori is done e.g., by Kerzenmacher (AMT, 2012).
HOWEVER, Kerzenmacher applies also a scaling to the extended profile (I guess to have a more continuous profile), and therefore the cancellation will not be perfect. One will have then something like

xrefsm_1 = A_11 xref_1 + (I -A_11) xa_1 + (b-1) * A_12 xa_2

with b the scaling factor. There was a small note on this on page 68 of the DPMv2. For the scaling factor approach itself, see section 9.8.2 .

**Comment by StevenCompernolle** [comment]
I discussed with Bavo and Arno about this. They would not use the profile scaling, as Kerzenmacher did. So simply extension with the a priori profile.

**Comment by svniemeijer** [comment]
The implementation has been updated for this.
