### ISSUE TITLE
Create variable conversion from 2D AVK/apriori to column AVK/apriori

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#116]
Implement variable conversions to derive a column averaging kernel from a (partial column) 2D averaging kernel (`colum_avk(i) = sum(j, ones(j) . partial_column_avk(j,i))`) and to derive a column a-priori from an a-priori profile (`column_apriori = apriori(i) - sum(i, partial_column_avk(i,j)) * apriori(j))`)

Update (see below): `column_apriori = sum(i, apriori(i))`

The `column_apriori` conversion is already available in HARP, so only the `column_avk(i)` conversion will need to be added. We need to combine this with #120 to also allow vmr/mmr/nd AVKs to be used as input.

**Comment by StevenCompernolle** [comment]
I understand `colum_avk(i) = sum(j, ones(j) . partial_column_avk(j,i))`
But why not `column_apriori = sum(i,apriori(i))` ?
I would say that `sum(i, apriori(i)) - sum(i, partial_column_avk(i,j)) * apriori(j))` gives the portion of the a priori column that should be added to the sensed column `sum(i, partial_column_avk(i,j)) * xtrue(j))` but it is not the total a priori column.

**Comment by svniemeijer** [comment]
You are right. I have been struggling with this part as well. The point is that for 2D smoothing one needs the 2D AK + 1D apriori. But what do we use as input for the smoothed column integration? We have the 1D column AK, but how do we represent the apriori? If this has to be a single 0D quantity then it will have to be the difference. The other option, which is probably what we need to go for is to use the 1D apriori (partial column) profile as input for the smoothed column integration.

With that approach, we won't need a special treatment for the column apriori and just use ``column_apriori = sum(i, apriori(i))``

Inputs for the smoothed column integration then need to be the 1D column AK and the 1D apriori profile (as partial columns)

**Comment by svniemeijer** [comment]
Note that this is also linked to the GEOMS templates. It means we should verify that for column quantities that come with a 1D column AVK, there should also be a 1D partial column apriori. Having a 0D column apriori would be useless.

**Comment by StevenCompernolle** [comment]
Agreed with  
`column_avk(i) = sum(j, ones(j) . partial_column_avk(j,i))`
and with 
`column_apriori = sum(i,apriori(i))` 

In general, for a 1D column AVK there is also a 1D apriori needed. But there is an exception: see QA4ECV NO2 where it chosen not to provide `apriori(i)` because `partial_column_avk(j,i).apriori(i)=sum(i,apriori(i))`, and hence the whole a priori part cancels in the 'smoothing equation'.
