### ISSUE TITLE
Add averaging kernel conversions

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#120]
2D vertical averaging kernels for volume mixing ratios, number densities, and partial column densities, etc. are not the same. We should add conversions to convert one into the other.

For instance, ``O3_number_density_avk(i,j) = O3_volume_mixing_ratio_avk(i,j) * number_density(i) / number_density(j)``.

The conversion between ``O3_number_density_avk(i,j)`` and ``O3_column_number_density_avk(i,j)`` is a scaling with regard to the layer height.

AVKs for vmr and mmr are the same when they are relative to dry air, but when using total air a scaling with regard to the (vertically dependend) molar mass of air ratio is needed.

**Comment by StevenCompernolle** [comment]
Unit conversions for AK are treated in http://www.atmos-meas-tech.net/8/2093/2015/amt-8-2093-2015.pdf
See Table B1.
The case 'VMR to ND'  amounts to `O3_number_density_avk(i,j) = O3_volume_mixing_ratio_avk(i,j) * temperature(i)/pressure(i) / (temperature(j)/pressure(j))` which is indeed the same as `O3_volume_mixing_ratio_avk(i,j) * number_density(i) / number_density(j)`

**Comment by StevenCompernolle** [comment]
For the conversion 'ND to PC' you are not changing the size of the AK, right (i.e., only unit conversion, no regridding from N to N-1)?
Then indeed `O3_number_density_avk(i,j)` should be multiplied by the layer height, to get `O3_column_number_density_avk(i,j)`.

**Comment by svniemeijer** [comment]
The size of the AK for ND to PC conversion is indeed not modified (regridding is treated separately, see #106).
