### ISSUE TITLE
Introduce vertical shift of profile

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#188]
For some species, like HCHO or NO2, profile distribution tend to follow the orography.
So if SAT and REF profiles are compared, but the surface_pressure of both is different, this should lead to a vertical shift of one of the profiles rather than a cut-off. 
According to Zhou et al. www.atmos-meas-tech.net/2/401/2009/, the shift should be done such that VMR is preserved.
E.g., if the profile on the source grid has a peak near the surface, the profile on the target grid will have that as well. But the surface is at different height. See following figure (from fig 8 of Zhou et al.), with black and blue the profiles at different grids:
![image](https://user-images.githubusercontent.com/21082396/45204270-f91f4680-b27e-11e8-9661-37e61d3622c2.png)
Doing instead a cut-off of the profile (a possibility within HARP) could lead e.g., to the loss of the peak near the surface, and therefore a very different result.

The important formula of the article are (2) and (5). I'll give more detail in a next comment.

**Comment by StevenCompernolle** [comment]
In the Zhou article, the vertical grid (in pressure) is defined using hybrid level coefficients _a(l)_ and _b(l)_, and a surface pressure (HARP can already convert these from the source product to a `pressure_bounds` grid). Eq. (2) from Zhou:
![image](https://user-images.githubusercontent.com/21082396/45205282-feca5b80-b281-11e8-8f6c-7307f376f771.png)
![image](https://user-images.githubusercontent.com/21082396/45205302-0b4eb400-b282-11e8-8190-bfa9007a010b.png)
 (here p\_{TM4} is the `surface_pressure` of the source grid, p\_{b,l} is a layer bottom of the source grid, p\_{b,l} is a layer top of the source grid). The target grid is defined in the same way, using `surface_pressure` of the target. Therefore source grid and target grid have the same number of elements.
The next step is then Eq. (6), where the profile (in partial column) is transformed.
![image](https://user-images.githubusercontent.com/21082396/45205492-98920880-b282-11e8-9b61-aadf2486e100.png)
Here p\_{b,l} is a layer bottom of the source grid, p\_{b,l} is a layer top of the source grid, p^{eff}\_{b,l} is a layer bottom of the target grid, etc. x\_{a,l} is a source profile element (in partial column) and x^{eff}\_{a,l} is the corresponding target profile element.

The formula look all very simple. The main problem is probably the vertical grid definition, which is not general. How exactly should one shift a general `pressure_bounds` ? Perhaps in log(p)? And could one simply shift linearly an `altitude` ?

**Comment by svniemeijer** [comment]
I am afraid this doesn't look like something to implement in HARP.
The algorithm you mention seems like a 'correction' of a wrong grid. This is not scope for HARP. We will also not include algorithms to fix a wrong time grid or a wrong spectral grid.

The geospatial position is an integral part of the quantity. If that position is wrong, then it should be fixed within the dataset itself. And the paper that you reference is also exactly addressing this. It explains how to improve the surface pressure in the satellite data itself (it does not advocate applying corrections as part of a comparison).

Note also that the algorithm you ask for is not 'simple'. Any vertical grid adaptation will need to hold for all quantities that use that grid. This includes temperature, air density, altitude, etc.
Also, the paper uses a specific definition for p^{eff}, which is not the grid of a ground based measurement. It is a grid based on an adjusted surface pressure using 'a' and 'b' coefficients to derive the adjusted pressure grid. This is not the same as using some arbitrary pressure grid from a ground based measurement. Note also that HARP does not have the 'a' and 'b' coefficients anymore after ingestion of S5P data, so recalculating the S5P grid using a different surface pressure is not an option.

**Comment by svniemeijer** [comment]
I have some principal reservations against trying to modify the SAT profile as part of a comparison in that way (since you are no longer comparing the SAT data as provided, but some alternative retrieval of it), but this is not the forum to discuss that.

Note that it is still possible to create a separate script that would perform the correction as you described if you have access to the original L2 data products (which I know is not the case for your situation). The collocations csv file will give you to sample index and filenames of the L2 products from which you could then retrieve the a/b coefficients directly to adjust the grid.

**Comment by StevenCompernolle** [comment]
The a, b coefficients (from the TM5 model) are fixed in time. I have to copy them only once from a sample file. (But I did found different coefficients for S5P NO2 and S5P HCHO on one hand, and QA4ECV NO2 and QA4ECV HCHO on the other hand.)
