### ISSUE TITLE
Add stratospheric_no2_vertical_column_stream ingestion for QA4ECV NO2

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#200]
/PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/stratospheric_no2_vertical_column_stream
and 
/PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/stratospheric_no2_vertical_column_stream_uncertainty

could be added to HARP ingestion using a separate HARP ingestion option.

**Comment by StevenCompernolle** [comment]
Yes, what you suggest for ingestion option is what I had in mind.
Regarding the _avk, _amf question. I am not sure. I sent the question to Folkert, Henk and Steffen (the last one authored the STREAM method).

**Comment by StevenCompernolle** [comment]
No answer yet from them. I suggest to go ahead and not include the _avk and _amf, to avoid having an inconsistent product. Stratospheric _avk and _amf are not directly needed for our purposes anyway.

**Comment by svniemeijer** [comment]
There is no plan for a new harp release very soon, so please try to retrieve the answer still.
The initial part of this feature has already been implemented in f71821c80672b683117924832a4f11cbdeea38a9

**Comment by StevenCompernolle** [comment]
I just got the confirmation from Folkert:

> The STREAM-code was run on the QA4ECV original files and takes SCD, AMFstrat, cloud info as stored in the origina QA4ECV-files. So yes, they should be consistent with what is in the QA4ECV product.

**Comment by svniemeijer** [comment]
Great. Then what is currently implemented on the master branch is all that is needed.
This item will then be included in the next official release.
