### ISSUE TITLE
Add variables to OMI OMNO2 ingestion

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#201]
The following variables would be important to add, as it enables comparison with stratospheric NO2 from both TROPOMI NO2 and QA4ECV OMI NO2:

In `/HDFEOS/SWATHS/ColumnAmountNO2/Data_Fields/`
`VCDQualityFlags`  -> `validity`
`ColumnAmountNO2Strat`  -> `stratospheric_NO2_column_number_density`
`ColumnAmountNO2StratStd`  ->  `stratospheric_NO2_column_number_density_uncertainty`

The following would be nice-to-have:

`AmfStrat`  -> `stratospheric_NO2_column_number_density_amf`
`AmfTrop`   -> `tropospheric_NO2_column_number_density_amf`
`TropopausePressure` -> `tropopause_pressure`
`TerrainHeight`  -> `surface_altitude`
`TerrainPressure`  -> `surface_pressure`
  
`SlantColumnAmountNO2Destriped`  -> `slant_NO2_column_number_density` (possibly with harp ingestion option to switch to `SlantColumnAmountNO2`)
`SlantColumnAmountNO2Std`  -> `slant_NO2_column_number_density_uncertainty`
`SlantColumnAmountCHOCHO`  -> `slant_CHOCHO_column_number_density`
`SlantColumnAmountCHOCHOStd` -> `slant_CHOCHO_column_number_density_uncertainty`
`SlantColumnAmountH2O` -> `slant_H2O_column_number_density`
`SlantColumnAmountH2OStd`  -> `slant_H2O_column_number_density_uncertainty`
`VcdApStrat`  -> `stratospheric_NO2_column_number_density_apriori`
`VcdApTrop`  -> `tropospheric_NO2_column_number_density_apriori`

**Comment by svniemeijer** [comment]
Additional fields have been added.

CHOCHO/H2O SCDs have not been added.
They are considered a bit out of scope since there are also no VCDs for these quantities.
