### ISSUE TITLE
Add variable column_number_density with GEOMS MAXDOAS ingestion

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#202]
I noticed that for some MAXDOAS GEOMS files (e.g., bePRO MAXDOAS from Xianghe, the so-called QA4ECV v1 MAXDOAS data set, where both VMR and partial column profiles are available)
there is also the variable `COLUMN.PARTIAL_INDEPENDENT` explained as 
`Vertical profile of partial columns of dry air number densities (for conversion between VMR and partial column profile)`
These could be added in a HARP ingestion as `dry_air_column_number_density`

**Comment by svniemeijer** [comment]
We don't include this variable, because HARP can derive it for you from the temperature and pressure. If you want the column number densities then add a `derive(column_number_density {time,vertical} [molec/cm2])` operation step to the ingestion.

**Comment by svniemeijer** [comment]
Note that since the derivation seems to produce the same values as can be found in COLUMN.PARTIAL_INDEPENDENT, the column number density is not with regard to dry air (or the temperature is actually a virtual temperature?)
