### ISSUE TITLE
GEOMS NO2 ingestion: 'AOD=measured' option does not work

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#203]
When ingesting a GEOMS NO2 file (QA4ECV, v1 data containing NO2 profiles) with AOD unset,  
  `AEROSOL.OPTICAL.DEPTH.TROPOSPHERIC_INDEPENDENT`
is ingested as expected.
However, when using
`harpdump -o 'AOD=measured' groundbased_uvvis.doas.offaxis.no2_bira.iasb007_xianghe_20161220t001026z_20161220t075232z_002.hdf"`

the `tropospheric_aerosol_optical_depth` is not ingested, while `AEROSOL.OPTICAL.DEPTH.TROPOSPHERIC_SCATTER.SOLAR.OFFAXIS`
should have been ingested.

**Comment by svniemeijer** [comment]
Fixed in 380ede28a8ede15382273529a328bb227e988535
