### ISSUE TITLE
Document the use of .pth files for harp command line tools

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#204]
harpcollocate command explanation says "The path for a dataset can be either a single file or a directory containing files. "
However, it is also possible to use a .path file with a list of paths. Probably this is also true for other harp commands like harpmerge.
Perhaps I overlook it, but I don't find the use of .path files in the documentation.

**Comment by svniemeijer** [comment]
Fixed in cb8bc233e2f8e14f5e83d608d8fb9b2ce9c9233c
