### ISSUE TITLE
installation of version 1.6 fails with shared libraries

### ISSUE THREAD

**Issue by PhML** [stcorp/harp#205]
Since commit fffb0199e63fe2224ea2e24d704b8d3ec11a74b6 harp fails to run after `make install`:
```
$harpmerge
harpmerge: error while loading shared libraries: libharp.so.10: cannot open shared object file: No such file or directory
```
While `harpmerge` generated into the source directory works.

Tested on Ubuntu 16.04.

**Comment by svniemeijer** [comment]
Did you configure+build from a clean checkout?
Please make sure you do not reuse any partial build results from previous versions.
Also, if you use a git clone please make sure you call the bootstrap script again.

**Comment by PhML** [comment]
This is how I proceeded:
```
$ git clone --recurse-submodules https://github.com/stcorp/harp.git
$ cd harp
$ git bisect start HEAD 63a57
$ git bisect run ./test.sh
```
With the following content of `test.sh`:
```bash
#!/bin/bash
make uninstall
make clean
./bootstrap
./configure --enable-python PYTHON=/usr/bin/python --with-hdf4 HDF4_LIB=/opt/hdf4/lib/ HDF4_INCLUDE=/opt/hdf4/include/ --with-hdf5 HDF5_LIB=/usr/lib/x86_64-linux-gnu/hdf5/serial HDF5_INCLUDE=/usr/include/hdf5/serial
make
sudo make install
/usr/local/bin/harpmerge
```
It gave me:
```
fffb0199e63fe2224ea2e24d704b8d3ec11a74b6 is the first bad commit
commit fffb0199e63fe2224ea2e24d704b8d3ec11a74b6
Author: Sander Niemeijer <niemeijer@stcorp.nl>
Date:   Mon Apr 29 09:52:07 2019 +0200

    Prepare for new 1.6 release

:100644 100644 e3099937ee935c8de2e660fd89275a60cf69b426 68d87b0b04b8bb3dc895a1b08020ff859275502b M      CHANGES
:100644 100644 977804e7826dd6380286b6b235a71239ed628cbe 474f78837147d7a3db370af0c7d2292dd3705ea4 M      CMakeLists.txt
:100644 100644 cf61e062e51df7f6c51663f891e164da1420a335 ab9288dff5322b80bcec624b1af0e71426757b84 M      README
:100644 100644 04f2f374194ad69ca90d2eec868a70ee4cb729e8 bf2c0529aef92f28f872ba21da3c9847d72dc6d2 M      configure.ac
:040000 040000 3e30274926459ad14774fd59962adfa68190cab1 c23da967c539852d18ae671cbe4617a9398fb08d M      doc
bisect run success
```
I also tested the tar.gz from the release page.

**Comment by svniemeijer** [comment]
I can't reproduce your problem.

The bisect succeeds for me for every step.
I am using the following `test.sh` (having HDF4/HDF5/CODA installed in ~/local and also using ~/local as prefix for HARP):

```
#!/bin/bash
./bootstrap
./configure --enable-python --prefix=$HOME/local LDFLAGS=-L$HOME/local/lib CPPFLAGS=-I$HOME/local/include
make
make install
$HOME/local/bin/harpmerge
make uninstall
```

(note that the uninstall should be performed at the end, since it needs to use the same source base that you used for the install!)

Could you otherwise attach a full console output of the `make` + `make install` steps of a master checkout of HARP? And attach your config.log for that same build?
Probably something goes wrong with the installation of the libharp.so library

**Comment by svniemeijer** [comment]
Closed due to lack of responsive from initial poster.
