### ISSUE TITLE
trying to use harp from anaconda results in a segmentation fault

### ISSUE THREAD

**Issue by jgriesfeller** [stcorp/harp#206]
I am trying to use harp on Sentinel5P NO2 data.
I prepared conda with the following commands so that everything is in separate environment:
```
conda create -n sentinel5p
conda activate sentinel5p
conda config --add channels stcorp
conda install harp
```
As a product file I am using S5P_OFFL_L2__NO2____20181201T181348_20181201T195518_05879_01_010202_20181207T195919.nc
which is in this tar file: http://www.temis.nl/airpollution/no2col/data/tropomi/2018/12/tropomi_no2_20181201.tar
using the file with coda works fine:
```
codadump list S5P_OFFL_L2__NO2____20181201T181348_20181201T195518_05879_01_010202_20181207T195919.nc 
/METADATA/QA_STATISTICS/nitrogendioxide_stratospheric_column_histogram[100]
/METADATA/QA_STATISTICS/nitrogendioxide_stratospheric_column_histogram_axis[100]
/METADATA/QA_STATISTICS/nitrogendioxide_stratospheric_column_histogram_bounds[100,2]
/METADATA/QA_STATISTICS/nitrogendioxide_stratospheric_column_pdf[400]
/METADATA/QA_STATISTICS/nitrogendioxide_stratospheric_column_pdf_axis[400]
/METADATA/QA_STATISTICS/nitrogendioxide_stratospheric_column_pdf_bounds[400,2]
/METADATA/QA_STATISTICS/nitrogendioxide_total_column_histogram[100]
/METADATA/QA_STATISTICS/nitrogendioxide_total_column_histogram_axis[100]
/METADATA/QA_STATISTICS/nitrogendioxide_total_column_histogram_bounds[100,2]
/METADATA/QA_STATISTICS/nitrogendioxide_total_column_pdf[400]
/METADATA/QA_STATISTICS/nitrogendioxide_total_column_pdf_axis[400]
/METADATA/QA_STATISTICS/nitrogendioxide_total_column_pdf_bounds[400,2]
additional lines removed
```
but trying to use it with harp results in a seg fault:
```
harpdump -l S5P_OFFL_L2__NO2____20181201T181348_20181201T195518_05879_01_010202_20181207T195919.nc 
Segmentation fault (core dumped)
```

I am new to harp (but not coda), but is the harp package broken in anaconda?

This on a Linux machine running Ubuntu Bionic without any specialities.

Thanks for your help!

**Comment by svniemeijer** [comment]
I think we found the issue, which was in the HARP ingestion initialization.
It should be fixed with bf55bc5f04c3306b2d469a8ab96894a779e275d6.
We will issue a new HARP release with this fix soon.
