### ISSUE TITLE
harpdump exits with "ERROR: cannot open environment-specified unit database"

### ISSUE THREAD

**Issue by PHedelt** [stcorp/harp#207]
I am trying to use harp v1.8 on Sentinel5P SO2 data.
When using the command-line tools (harpdump, harpcheck, etc.) I am always getting the error

ERROR: cannot open environment-specified unit database ((null))

I have successfully installed HARP1.8 on my machine with HDF5 and HDF4 included (./configure --prefix=$HOME/harp --enable-idl IDL=$HOME/idl87/ CODA_LIB=$HOME/coda/lib64/ CODA_INCLUDE=$HOME/coda/include/ --with-hdf5 --with-hdf4)

How can I solve this error?

**Comment by svniemeijer** [comment]
This was clarified offline. It was due to a wrongly set UDUNITS2_XML_PATH environment variable.
