### ISSUE TITLE
Add quality flag for OMCLDO2 product

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#211]
Regarding OMCLDO2, reading the manual, it looks like the most general quality flag is ProcessingQualityFlags
at 
/HDFEOS/SWATHS/CloudFractionAndPressure/Data_Fields/

Could you add this as a validity variable? It is useful in comparing with TROPOMI CLOUD and FRESCO.

Likewise, for OMCLDRR, the general quality flag is 
ProcessingQualityFlagsforO3
at
/HDFEOS/SWATHS/Cloud_Product/Data_Fields/

**Comment by svniemeijer** [comment]
Implemented in 4a3ed080bbd23b6359ffce60d1b5176c0a8e555c
