### ISSUE TITLE
Add variables for S5P CLOUD 2.x

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#229]
Following variables would be interesting:

For CAL ingestion:
/PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/cloud_top_temperature
HARP name: cloud_top_temperature

Both ingestions:
/PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/cloud_phase
HARP name: cloud_type

**Comment by svniemeijer** [comment]
Implemented in f75542af20046768a585a75721115bdf707e15d9
