### ISSUE TITLE
Incompatibilities bewteen harp and geopandas

### ISSUE THREAD

**Issue by bilelomrani1** [stcorp/harp#231]
It seems that `harp` and `geopandas` cannot be installed in the same `conda` environement.
```bash
$ conda install geopandas harp
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): \ 
...
```
Is there a fundamental reason why these two packages do not interact well with each other? And is there something that we can do to install `harp` alongside `geopandas`. For scripting purposes, I want to have both packages in the same env.

**Comment by svniemeijer** [comment]
You need to provide the `stcorp` channel if you want to install harp:

```
$ conda install -c stcorp geopandas harp
```

**Comment by bilelomrani1** [comment]
Sorry, to clarify I added the `stcorp` channel globally

**Comment by svniemeijer** [comment]
I created a new conda environment and was able to install both packages within that environment.
It did take a while for conda to solve the environment, but it succeeded in the end.
If you get an error, then please show the error.

**Comment by bilelomrani1** [comment]
I ended up using the following
```bash
conda install --override-channels -c stcorp -c conda-forge geopandas harp
```
otherwise `conda` took ages to resolve. Thanks for your help!
