### ISSUE TITLE
documentation issue harp_geometry_has_area_overlap

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#240]
On the harp documentation pages (https://cdn.rawgit.com/stcorp/harp/master/doc/html/libharp_geometry.html), I see as first line for harp_geometry_has_area_overlap

"Determine whether a point is in an area on the surface of the Earth"

This is the explanation for the routine "harp_geometry_has_point_in_area"
Probably here should be something like "Determine if two polygons overlap and calculation the fractional overlap".

**Comment by svniemeijer** [comment]
Thanks for pointing this out. Fixed in ac96164b874c13379bd33021499b73e725e1fc3f
