### ISSUE TITLE
Python Error when running harp library

### ISSUE THREAD

**Issue by whositwhatnow** [stcorp/harp#244]
I'm getting the following error when running my code using the harp library:

Traceback (most recent call last):
File "2_process_netcdf_python.py", line 20, in <module>
no2_l3 = harp.import_product(i,operations=harp_op)
File "/opt/harp/1.13/lib/python3.8/site-packages/harp/_harppy.py", line 1217, in import_product
raise CLibraryError()
harp._harppy.CLibraryError: syntax error, unexpected FUNC_KEEP, expecting $end

Can't figure it out, anyone possibly see this error before?

**Comment by svniemeijer** [comment]
Please post support requests on https://forum.atmospherictoolbox.org

The error you are seeing is a problem in your harp_op string. Maybe you are missing a ';' separator?

**Comment by whositwhatnow** [comment]
thank you, Ill bookmark that page.
