### ISSUE TITLE
Comparison of OMI level 2 NO2 profile with WRF_Chem simulations

### ISSUE THREAD

**Issue by pubali89** [stcorp/harp#247]
Hi  
I am trying to compare WRF_Chem simulated NO2 with that of OMI NO2 profiles; I understand that level 2 OMI swath data should be used for this purpose, where OMI averaging kernel should be used. I have been stuck with this issue for a long time, any help regarding the procedure will be highly appreciated, if required we can connect regarding co-authorship on the publication resulting from this research.
Eagerly awaiting for a response.

**Comment by svniemeijer** [comment]
Please post questions like these on the [forum](https://forum.atmospherictoolbox.org).
This issue tracker is only meant for improvements on the harp software itself.
