### ISSUE TITLE
Add support for `geolocation_flags` of S5P NO2 product

### ISSUE THREAD

**Issue by zxdawn** [stcorp/harp#254]
I discussed with Henk Eskes last week and we thought that the `geolocation_flags` is useful to filter ascending/descending data and determine sun glint. It would be great to add it to harp.

**Comment by svniemeijer** [comment]
It is not a straight ascending/descending split, but it does split the orbit in two.
Why would you need to know this explicit asc/desc split?

**Comment by svniemeijer** [comment]
If you are splitting at the asc/desc split you will just get dividing lines somewhere else, so I doubt that that will fix it for you.
