### ISSUE TITLE
Add support for additional OCO-2 L2 and OCO-3 L2 products

### ISSUE THREAD

**Issue by PowderL** [stcorp/harp#256]
Is there any possibility to add support for additional OCO-2 L2 and OCO-3 L2 products?

**Comment by svniemeijer** [comment]
For sure. If you can let us know which one(s) you want, we can see if these can be added.

**Comment by PowderL** [comment]
> For sure. If you can let us know which one(s) you want, we can see if these can be added.

Actually, the two satellite datasets have the same file structure，supportting one of them meets the requirements. But the L2 product cluster consists of several products, as [`Lite_FP`](https://disc.gsfc.nasa.gov/datasets/OCO2_L2_Lite_FP_10r/summary?keywords=oco-2) is prepared for most users, could you please firstly add support for the [`Lite_FP`](https://disc.gsfc.nasa.gov/datasets/OCO2_L2_Lite_FP_10r/summary?keywords=oco-2)  product?

**Comment by svniemeijer** [comment]
This was introduced in HARP V1.16
