### ISSUE TITLE
Unable to install from conda

### ISSUE THREAD

**Issue by varishtsg** [stcorp/harp#257]
While installing from conda, I get the error message saying that the user stcorp cannot be found.

https://conda.anaconda.org/stcorp

Installing using conda gives the following error:

  UnavailableInvalidChannel: The channel is not accessible or is invalid.
    channel name: stcorp
    channel url: https://conda.anaconda.org/stcorp
    error code: 404
  
  You will need to adjust your conda configuration to proceed.
  Use `conda config --show channels` to view your configuration's current state,
  and use `conda config --show-sources` to view config file locations.

**Comment by svniemeijer** [comment]
harp is now available from the conda-forge channel. And only from that channel.

**Comment by varishtsg** [comment]
The documentation needs to be updated. http://stcorp.github.io/harp/doc/html/install.html#using-anaconda this still points to using stcorp channel instead of conda-forge.

**Comment by svniemeijer** [comment]
Thanks for spotting this. We just fixed it.
