### ISSUE TITLE
Is there any possibility for producing map all time samples onto a spatial latitude/longitude grid for a product beyond the support product list?

### ISSUE THREAD

**Issue by PowderL** [stcorp/harp#258]
I am dealing with products from OCO-2 and GOSAT. Fortunately, the harp does support the product of GOSAT but does not support the product of OCO-2. I have a try to rewrite a GOSAT product file using data from OCO-2. I just replace the listed variables used for mapping [GOSAT data product](http://stcorp.github.io/harp/doc/html/ingestions/GOSAT_FTS_L2_CO2_TC.html). But I failed to get convincing results. I think the reason should be that I only replace several geolocation variables including **longitude**, **latitude**, **longitude_bounds**, **latitude_bounds**, and my concerned variable **CO2_column_number_density** in the GOSAT product file with the similar variables from the OCO-2 product file. Therefore, the replacements should be insufficient. Is there any possibility to generate a fake product file by replacing the original values of the geolocation variable and concerned variable with values from another unsupported product file? This should help support more product files.

**Comment by svniemeijer** [comment]
Support for OCO-2 is planned (see #256).
However, you can always create your own 'harp converter' if you want. But that would be more a 'usage' question that would be a topic for [the toolbox forum](https://forum.atmospherictoolbox.org).

**Comment by PowderL** [comment]
OK, thanks for your quick reply!
