### ISSUE TITLE
Problem importing multiple products

### ISSUE THREAD

**Issue by Pratik-Bhatt190** [stcorp/harp#265]
I want to process multiple sentinel S5p products with the harp. But it is showing some kind of error. when I am importing a single product, it is working fine, but whenever I am trying to import multiple products it is showing the following error:

The error is generating against this lines of code:
for i in range (len(input_files)):
    Converted_O3=harp.import_product(input_files[i],\
                                     operations= "latitude <= -40[degree_north];\
                                     keep(latitude,latitude_bounds,longitude,longitude_bounds,\
                                     O3_column_number_density,O3_column_number_density_validity,datetime_start)")

CLibraryError                             Traceback (most recent call last)
Input In [6], in <cell line: 1>()
      1 for i in range (len(input_files)):
----> 2     Converted_O3=harp.import_product(input_files[i],\
      3                                      operations= "latitude <= -40[degree_north];\
      4                                      keep(latitude,latitude_bounds,longitude,longitude_bounds,\
      5                                      O3_column_number_density,O3_column_number_density_validity,datetime_start)")

File ~\Anaconda3\envs\spatial\lib\site-packages\harp\_harppy.py:1293, in import_product(filename, operations, options, reduce_operations, post_operations)
   1290 # Import the product as a C product.
   1291 if _lib.harp_import(_encode_path(filename), _encode_string(operations), _encode_string(options),
   1292                     c_product_ptr) != 0:
-> 1293     raise CLibraryError()
   1295 try:
   1296     # Raise an exception if the imported C product contains no variables, or variables without data.
   1297     if _lib.harp_product_is_empty(
![Screenshot (33)](https://user-images.githubusercontent.com/103387711/163723736-0790da7c-92b6-4016-a3b3-f8796f5f96d8.png)
![Screenshot (33)](https://user-images.githubusercontent.com/103387711/163723777-12059a90-e6d9-4e86-95be-6690f8318d79.png)
c_product_ptr[0]) == 1:

CLibraryError: [HDF5] H5Z__filter_deflate(): inflate() failed (major="Data filters", minor="Unable to initialize object") (D:\bld\hdf5_split_1646412567021\work\src\H5Zdeflate.c:118)

For your information, I have installed all the packages in a new environment.
Thanks & Regards

**Comment by svniemeijer** [comment]
This looks like the same issue as https://forum.atmospherictoolbox.org/t/unable-to-read-selected-s5p-l2-hcho-files/43
Please try downloading the failing product(s) again
