### ISSUE TITLE
Extend input for harp.import_product to .pth files

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#269]
Currently harp.import_product allows for a filename, list of filenames, a globbing (glob.glob()) pattern, or a list of globbing patterns.

In analogy to the commandline harpmerge, it would be handy if a .pth file (or list of .pth files) would also be allowed.

Of course, with some extra coding within python, one could first import the .pth file and convert to a list of filenames, and then put this as input to harp.import_product. But it would be easier if the harp python interface could directly do this.

**Comment by svniemeijer** [comment]
Good idea. We will add it to the list.

**Comment by svniemeijer** [comment]
Implemented in fec035a60186e6baeae026ffec6aaa56a0652a8d
