### ISSUE TITLE
No support oco3_LtCO2 in harp v1.15.1?

### ISSUE THREAD

**Issue by gc13141112** [stcorp/harp#274]
I want to process oco3_LtCO2 products with the harp. But it is showing some kind of error. 
 The error is generating against this lines of code:
   data = harp.import_product('oco3_LtCO2_220429_B10400Br_220607224712s.nc4')
  File "D:\miniconda3\lib\site-packages\harp\_harppy.py", line 1300, in import_product
    raise CLibraryError()
harp._harppy.CLibraryError: oco3_LtCO2_220429_B10400Br_220607224712s.nc4: unsupported product

**Comment by svniemeijer** [comment]
OCO support is not available in v1.15.1. It will be available in the next official release of HARP.
If you already want to use the functionality before that then you will have to build HARP from github source.

**Comment by gc13141112** [comment]
I have built HARP from github source and can open oco3_LtCO2_220429_B10400Br_220607224712s.nc4 with harpdump, but did't open with python. Did you know this error?
[root@node1 harp_install]# harpdump oco3_LtSIF_220429_B10309r_220607224911s.nc4 | more
dimensions:
    time = 197926

attributes:
    source_product = "oco3_LtSIF_220429_B10309r_220607224911s.nc4"

variables:
    double datetime {time = 197926} [seconds since 1990-01-01]

[root@node1 harp_install]# python oco3_read.py 
  RuntimeWarning,
Traceback (most recent call last):
  File "oco3_read.py", line 5, in <module>
    data = harp.import_product('oco3_LtSIF_220429_B10309r_220607224911s.nc4')
  File "/home/gaochao/model/LIBRARY/python3/lib/python3.6/site-packages/harp/_harppy.py", line 1300, in import_product
    raise CLibraryError()
harp._harppy.CLibraryError: oco3_LtSIF_220429_B10309r_220607224911s.nc4: unsupported product
