### ISSUE TITLE
No support oco2_LtCO2 in github version?

### ISSUE THREAD

**Issue by gc13141112** [stcorp/harp#276]
I have built HARP from github source and can open oco3_LtCO2 but not open oco2_LtCO2. Did you know this error?
Traceback (most recent call last):
  File "oco3_read.py", line 15, in <module>
    data = harp.import_product('oco2_LtCO2_220531_B11014Ar_220822215124s.nc4')
  File "/home/gaochao/model/LIBRARY/python3/lib/python3.6/site-packages/harp/_harppy.py", line 1300, in import_product
    raise CLibraryError()
harp._harppy.CLibraryError: can not read uint64 data using a int32 data type

**Comment by svniemeijer** [comment]
Confirmed. We had only added support for v10. We will add v11 (and v9, if possible).

**Comment by svniemeijer** [comment]
Should be fixed in https://github.com/stcorp/harp/commit/d938ba8c504d0e785f9981e7220d16cf4750adcb

**Comment by gc13141112** [comment]
Thanks, I rebuilt this version and this data (v11 and v9) can be read.
