### ISSUE TITLE
Documentation on how to add support for new data products

### ISSUE THREAD

**Issue by a-schneider-fmi** [stcorp/harp#277]
Can you please document how I can add support for new data products? I couldn't find the required information in the docs. In particular, I would like to add support for my TROPOMI HDO data product (https://tropomi.grid.surfsara.nl/hdo/).

**Comment by svniemeijer** [comment]
HARP has built-in support to import data from a variety of different product types. Adding to this list requires extending the HARP code and requires detailed knowledge of the internal HARP ingestion system. This is usually not something that users should do and would therefore not be something that we would document in the end-user documentation.

Note however that you can easily create your own ingestion routine using the HARP python interfaces. There is a [post on the Atmospheric Toolbox forum](https://forum.atmospherictoolbox.org/t/add-additional-support-for-more-product-files-by-producing-similar-product-files-with-already-supported-product-files/444/2) that describes how to do this.

I would recommend that if you have any further specific usage questions that you ask this on the forum.
