### ISSUE TITLE
harp._harppy.CLibraryError？How to solve this bug?

### ISSUE THREAD

**Issue by gladnire** [stcorp/harp#279]
I want to process S5P_NRTI_L2__O3_____ products with the harp. But it is showing some kind of error.
The code was working fine, but suddenly this bug appears.

File "/root/anaconda3/envs/s5p2/lib/python3.7/site-packages/harp/_harppy.py", line 1300, in import_product
    raise CLibraryError()
harp._harppy.CLibraryError: record does not contain a field named 'degrees_of_freedom'

**Comment by svniemeijer** [comment]
Can you let me know which product you are trying to read?

**Comment by gladnire** [comment]
> S5P_NRTI_L2__O3_____20220915T031314_20220915T031814_25505_03_020401_20220915T035326.nc 
AND I got the same error when process L2__SO2___

**Comment by svniemeijer** [comment]
I can't reproduce this. What harp version are you using?

Also, I don't believe that you are getting the exact same error L2__SO2___, since degrees_of_freedom is only applicable to the O3 products.

**Comment by gladnire** [comment]
> I can't reproduce this. What harp version are you using?
> 
> Also, I don't believe that you are getting the exact same error L2__SO2___, since degrees_of_freedom is only applicable to the O3 products.

Thank you very much for your reply!!!
I used 1.11 version,now I have upgraded to the latest version.
The error for "L2_SO2__"is harp._harppy.CLibraryError: record does not contain a field named 'aerosol_index_340_380'

**Comment by svniemeijer** [comment]
Do you still have any of these issues with HARP 1.15.1?

**Comment by gladnire** [comment]
> 

YES!!!

**Comment by svniemeijer** [comment]
Then please check your installation again and make absolutely sure you are using the latest HARP version, because as I mentioned, I can't reproduce the errors you are seeing.

**Comment by gladnire** [comment]
> Then please check your installation again and make absolutely sure you are using the latest HARP version, because as I mentioned, I can't reproduce the errors you are seeing.

OK~Thank you! I will check my HARP version again~
