### ISSUE TITLE
How to use the harpcollocate resample to nc file?

### ISSUE THREAD

**Issue by funny000** [stcorp/harp#281]
Hi:
**harpcollocate version=1.6.0** 
i use python to use the harpcollocate command tool.
the script of python is follows.
import os
input_nc = "./data/omi_data.nc"
out_nc = "./data/omi_out.nc"

com_str = harpcollocate --resample f"{input_nc}" f"{out_nc}"
os.system(com_str)

- but run it after give me the error information: **ERROR: error reading 'collocation_index' in header**
**-how do solve the error?**

**Comment by svniemeijer** [comment]
Please use the [forum](https://forum.atmospherictoolbox.org) for support questions.
The github issue tracking is only meant for actual issues with or improvements to the harp source code.
