### ISSUE TITLE
Nan values in HARP

### ISSUE THREAD

**Issue by makr-a** [stcorp/harp#284]
Hello everyone, 
Pascal Hedelt sent me the Link to your Github. I am working with TROPOMI COBRA Data and trying to compare them to model Data. That's why while regridding the data and plotting them, I got some inconsistencies in the box and I think it is because of Nan values. How doese HARP deal with those values and what does he do when he finds Nan values in a Gricell. 

Thank you in advance, 
Ismail Makroum

**Comment by svniemeijer** [comment]
Hi Ismail,
This is actually a better question to ask on the [forum](https://forum.atmospherictoolbox.org).
If you have NaN value in the regridding then the result will also be NaN. So you need to make sure that you filter out all NaN values before performing the regridding (e.g. `valid(<variable_name>)`).

**Comment by makr-a** [comment]
Hello Sander,
ja I do that. But what happens then if I make QA_Flag>0.5? How is he handling that in the regridding?

Thank you in advance.
Ismail

Von: Sander Niemeijer ***@***.***>
Gesendet: Donnerstag, 16. Februar 2023 10:52
An: stcorp/harp ***@***.***>
Cc: Makroum, Ismail ***@***.***>; Author ***@***.***>
Betreff: Re: [stcorp/harp] Nan values in HARP (Issue #284)


Hi Ismail,
This is actually a better question to ask on the forum<https://forum.atmospherictoolbox.org>.
If you have NaN value in the regridding then the result will also be NaN. So you need to make sure that you filter out all NaN values before performing the regridding (e.g. valid(<variable_name>)).
