### ISSUE TITLE
HARP core dump when executing 'index(independent)==0'

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#295]
I tried the following:

When executing the following operation on a HARP-compatible file (with variables which have an independent_52 dimension), I got the following 

```
~ > harpconvert -a 'index(independent)==0' gome2a_NO2_20070123_01360_OVPHARP.nc out.nc
double free or corruption (out)
Aborted (core dumped)
```

As a practical problem: when doing this using harp.import_product on a jupyter notebook, the jupyter notebook cell seems to run forever; not registering that the command had actually failed.

I did not really expect a sensible outcome, since different independent dimensions can occur in the same harp file (e.g., `independent_4` for pixel bounds and `independent_52` for different stations for which I keep overpasses) which are all named as `independent` within the HARP operations. But then it would be better that HARP throws an error.

It would actually be interesting to be able to be able to filter on the dimension index of different independent dimensions. But as currently these different dimensions are made anonymous (all called 'independent') this seems impossible. Would it not be a good idea to allow user-specified named non-HARP dimensions (just like there can also be non-HARP variable names), which for the HARP routines would then just act like independent dimensions?

**Comment by svniemeijer** [comment]
The segmentation fault is fixed in bdf6657afa1af9c7b560826a21cef24af47a8510.
Performing an index filter on an independent dimension shouldn't have been allowed in the first place, so HARP now gives an error message if you try this.
