### ISSUE TITLE
harp.export_product can yield harp-incompatible file with no data

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#298]
I used harp.export_product in the python interface with the operations keyword, where I introduced some filtering.
It occurred that the filter retained no data, but still a file was produced. This seems unexpected behaviour as filtering using the command-line tools produces no file in such a case.

Moreover, the produced file is not compatible with HARP. Using such file as input to the harpconvert tool, or as input to the harp.import_product function of the python interface, yields an error, complaining about a zero-length variable.
(With harp.import the exact message is: NoDataError: product contains no variables, or variables without data)

**Comment by StevenCompernolle** [comment]
I used HARP 1.19.

**Comment by svniemeijer** [comment]
Fixed in af81c87565894d57e917b725e6a01ace9440e0d3

We are now throwing a `NoDataError` exception if you try to export an 'empty' product.
