### ISSUE TITLE
Deal with variable length profiles in profile regridding/smoothing

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#30]
Vertical profiles can have a different number of points per time index.
The regridding/smoothing operation should take this into account by omitting any points at the end for which the chosen axis variable has a NaN value.

**Comment by ElessarWebb** [comment]
Should all NaN points be omitted or only those that appear in the suffix of the vertical grid?
I.e. should the first NaN be treated differently than the others in the following vertical grid vector:

`[ 0, 1, NaN, 2, 3, NaN, NaN, NaN ]`

**Comment by svniemeijer** [comment]
Yes. Only the trailing NaNs determine the length of the vertical grid.
