### ISSUE TITLE
python harp.execute_operations "hangs" when latitude_bounds/longitude_bounds contain Fill values

### ISSUE THREAD

**Issue by PHedelt** [stcorp/harp#312]
I am using the Python interface of harp v1.19 to regrid a list of harp products to a common grid using the harp.execute_operations function.

I realized harp gets stuck, when a single value in the harp product is not finite. 
The problem is that it does not throw an error or exception  - the process simply hangs, it never ends but runs forever.

It took me quite a while to find the reason for the hanging harp process. 
I would expect that harp gracefully fails in this case

**Comment by svniemeijer** [comment]
Can you please check if you have the same problems with the latest HARP release (1.24)? We generally don't support older HARP releases.

Also, can you provide a minimal example that triggers this problem?

**Comment by PHedelt** [comment]
I can confirm that it’s the same issue with HARP 1.24.

 

I digged deeper into this issue and must update the cause of the issue. 

It wass not related to non-finite values, but to FillValues in either the latitude and/or longitude fields

 

Here is minimal example in which the latitude_bounds and longitude_bounds contain one FillValue:

 

```

product=harp.Product()

product.longitude = harp.Variable( np.array([74.01832]),["time"])

product.longitude.unit='degree_east'

product.latitude = harp.Variable( np.array([-107.81131]),["time"])

product.latitude.unit='degree_north'

product.longitude_bounds = harp.Variable( np.array([[-1.1381140e+02, -1.1253237e+02,  9.9692100e+36, -9.9201447e+01]]),["time",None])

product.longitude_bounds.unit='degree_east'

product.latitude_bounds = harp.Variable( np.array([[7.3761742e+01, 7.3744255e+01, 9.9692100e+36, 7.4081558e+01]]),["time",None])

product.latitude_bounds.unit='degree_north'

product.variable = harp.Variable( np.array([10]),["time"])

product.variable.unit=''

rebinned=harp.execute_operations([product],post_operations='bin_spatial(181,-90,1,361,-180.,1);derive(latitude {latitude});derive(longitude {longitude})')

```

 

Von: Sander Niemeijer ***@***.***> 
Gesendet: Donnerstag, 5. Dezember 2024 15:11
An: stcorp/harp ***@***.***>
Cc: Hedelt, Pascal Andre ***@***.***>; Author ***@***.***>
Betreff: Re: [stcorp/harp] python harp.execute_operations "hangs" when input data contain non-finite values (Issue #312)

 

Can you please check if you have the same problems with the latest HARP release (1.24)? We generally don't support older HARP releases.

Also, can you provide a minimal example that triggers this problem?

**Comment by svniemeijer** [comment]
Ok. We will see if we can somehow check for such excessive values.

However, be aware that HARP does not allow invalid values for axis variables (except for filling out the trailing part of time varying dimensions; see bottom section of the [HARP dimensions documentation](http://stcorp.github.io/harp/doc/html/conventions/dimensions.html).
But, such fill values for floating point values should be NaN and not some floating point specific minimum/maximum value.

**Comment by svniemeijer** [comment]
I've implemented some changes that eliminates the 'hanging' behaviour: aa52e55f4105a218cfe20a0236104481d816a1ee
It will not give you valid results though ('garbage in' remains 'garbage out') so you still have to get your data products fixed independently.
