### ISSUE TITLE
Convert tools to commands

### ISSUE THREAD

**Issue by ElessarWebb** [stcorp/harp#35]
```
harpconvert ... -> harp convert ...
harpcheck ...    -> harp check ...
harpcollocate   -> harp collocate
```

We can unnest some of the commands/options that existed in the original tools.
For example:

```
harpconvert --list-conversions -> harp list-derivations
```

**Comment by svniemeijer** [comment]
We are probably not going to do this anymore (we can reopen this issue again if we ever think it would be useful).
The list-conversions option has been renamed to list-derivations, though.
