### ISSUE TITLE
Add operation to collapse dimension

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#36]
Introduce an operation (``flatten()``) that will flatten a product in one (or more) dimensions. This allows variables that are [time,latitude,longitude] to be turned into a [time] variable or a [time,vertical] to be turned into a [time] veriable.
This is needed for collocation routines where e.g. data from a single lat/lon location from a gridded product is needed. The approach for this is to perform a lat/lon filter on the gridded [time,latitude,longitude] data, which will result in very small lat/lon dimensions, and then trough a flattening operation turn this into flat [time] data (where the length of [time] is the product of the original time, latitude, and longitude lengths).

Since this operation extends the time dimension, it will invalidate the 'index' variable and any collocation result files that applied to the product. The operation should thus remove both the 'index' and 'collocation_index' variables if these existed.

Any variables that depend more than once on the flattened dimension will be removed from the product (e.g. vertical averaging kernels will be removed if the vertical dimension is flattened)

**Comment by ElessarWebb** [comment]
I expect that this operation will also have a LIBHARP_API interface, e.g:

```
LIBHARP_API int harp_product_flatten_dimension(harp_product *product, char *dimension_name);
```
