### ISSUE TITLE
Align HARP HDF5 format with netCDF4 format

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#4]
HARP currently uses a 'dims' attribute to store dimension information. HDF5 seems to use 'dimension scales' (http://www.unidata.ucar.edu/software/netcdf/docs/interoperability_hdf5.html). We should try changing the HARP HDF5 storage format to use this convention as well.
This will then hopefully be sufficient to also allow HARP HDF5 files to be read/written using netCDF4.

**Comment by 0xA000** [comment]
Fixed in 8ed845bff2918fa033fe781bb7f9116525ee5f34
