### ISSUE TITLE
Create grouping of product ingestions

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#44]
We should create a 'product class' grouping of the products that we can ingest with HARP (linked one-to-one with how CODA groups products). This grouping is then to be used in the generated HARP documentation to get rid of the too long list of product conversions.

The ingestion definitions HTML page should contain the listing of product classes.
Then for each class there should be a separate page listing the supported product types and the conversions for each product type.
And then for each product conversion we again have the (already currently existing) separate page describing that specific conversion.

**Comment by 0xA000** [comment]
Fixed in 9ea1bb05695b2311a3e659f897e931aca61e6d9e.
