### ISSUE TITLE
Add bitflag filtering

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#6]
In order to properly filter on validity flags we need some way to mask bits in the bitfield.

We need a way to do this without having to manipulate the data itself. i.e. we don't want to have to perform any algebra on either the left or right hand side of a comparison, as this is both complicated to implement and would require more memory to store intermediate results.

Probably the easiest way to implement this is to have a bitmask comparison operator.
Perhaps we could introduce a '=&' and '!&' operator. a =& b would mean 'a&b != 0' and a!&b would mean (a&b == 0). Alternatively we could use functions instead of operators for these two cases.

**Comment by 0xA000** [comment]
Fixed in dd6e5ab64b5da08903157d25a0ef612f7c8695dc
