### ISSUE TITLE
Add support for OSIRIS L2

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#60]
Add harp ingestion for ODIN/OSIRIS Level 2 products

This will be a migration of the following BEAT-II ingestions:
- [x] [OSIRIS_L2_Aerosol_MART](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_Aerosol_MART)
- [x] [OSIRIS_L2_NO2_OE](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_NO2_OE)
- [x] [OSIRIS_L2_NO2_MART](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_NO2_MART)
- [x] [OSIRIS_L2_O3_OE](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_O3_OE)
- [x] [OSIRIS_L2_O3_MART](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_O3_MART)

More information is on the [OSIRIS website](http://odin-osiris.usask.ca/?q=node/280)

**Comment by svniemeijer** [comment]
These will be a migration of the BEAT-II [OSIRIS_L2_Aerosol_MART](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_Aerosol_MART), [OSIRIS_L2_NO2_OE](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_NO2_OE), [OSIRIS_L2_NO2_MART](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_NO2_MART), [OSIRIS_L2_O3_OE](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_O3_OE), and [OSIRIS_L2_O3_MART](http://www.stcorp.nl/beat/documentation/beatl2-data/index.html#OSIRIS_L2_O3_MART) ingestions.

**Comment by BartSchipperijn** [comment]
The requested ingestion of ODIN/OSIRIS L2 products has been added to the HARP code.
