### ISSUE TITLE
Move documentation of operation list expressions to HARP manual

### ISSUE THREAD

**Issue by 0xA000** [stcorp/harp#70]
At the moment, operation list expressions are documented as part of the HARP command line tools that use them (harpconvert, harpfilter). This documentation should be moved to a central place (the HARP manual). The usage information of the command line tools should then simply refer to the HARP manual for details. Perhaps it could still include a couple of examples for common tasks.

**Comment by svniemeijer** [comment]
Make sure to also include a description of the area-mask-file
