### ISSUE TITLE
Dealing with unspecified units in operations

### ISSUE THREAD

**Issue by 0xA000** [stcorp/harp#71]
At the moment, when units are unspecified in operations that are to be applied to a product, the unit of the corresponding variable is used. (For example, consider the expression "pressure > 1". The unit of the right hand side will be assumed to be the same as the unit of the left hand side.)

This approach can produce unintended results when operating on several products using the same expression, where the unit of the corresponding variable (e.g. pressure) differs from product to product.

Should we instead use the default HARP unit for the corresponding variable? (This requires that such a default unit is assigned to each variable supported to HARP.) Or, alternatively, should we disallow leaving the unit unspecified?

**Comment by svniemeijer** [comment]
There will anyway be comparisons against variables that may not have unit, so we can't enforce that values against which we are comparing always come with a unit.

The idea is that a comparison can be perform in two ways: either in a 'dumb' way, using just the values as provided, or in a 'unit consistent way' in which case the user has to provide a unit for the value, but the variable then has to come with a unit as well.

So, the current implementation is as intended. It is up to the user to decide whether a unit consistent comparison is needed or not.
