### ISSUE TITLE
Dealing with fill values in ingestion modules

### ISSUE THREAD

**Issue by 0xA000** [stcorp/harp#72]
Recent ingestion module implementations replace values equal to the _FillValue of a variable with the HARP default fill value corresponding to the data type of the variable. The default fill value for all integer types is 0, for floating point types it is NaN.

The valid range and _FillValue of a variable can be chosen independently. Therefore there could be products that have a _FillValue inside the valid range. However, the most common case seems to be that _FillValue is a value outside of the valid range.

See also the [netCDF attribute conventions](http://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html), under _FillValue:

> Generic applications often need to write a value to represent undefined or missing values. The fill value provides an appropriate value for this purpose because it is normally outside the valid range and therefore treated as missing when read by generic applications. It is legal (but not recommended) for the fill value to be within the valid range.

For variables of an integer type, if _FillValue is outside the valid range of the variable and 0 is inside, this replacement would implicitly convert invalid to valid values.

For variables of floating point type , if _FillValue is inside the valid range of the variable, this replacement would implicitly convert valid to invalid values.

Therefore, would it not be better to remove such replacements and just pass all values through as is, including values equal to _FillValue?

It seems such an approach better captures the intent of the original product. However, since HARP does not support a variable specific fill value, the information that a given value is a passed through fill value will be lost.

**Comment by svniemeijer** [comment]
The interpretation of a _FillValue should be done on a case-by-case basis. It is part of the mapping we perform to harp. If a _FillValue is indicating an invalid value (and this is not already NaN) than we map it to NaN.

The whole idea of HARP is also that we get rid of the product-specific conventions as part of the ingestion. We want to convert to a harmonised approach on how we represent invalid values in a HARP product.
