### ISSUE TITLE
Fix GOSAT FTS L1b ingestion for night-time products 

### ISSUE THREAD

**Issue by 0xA000** [stcorp/harp#79]
The implementation for night-time products, both observation modes I/II and target mode, needs to be fixed. Night-time products only have TIR (band 4). When selecting any of the other bands, return an empty product instead of propagating a CODA error.

Also check compatibility with format of latest L1B products.

**Comment by BartSchipperijn** [comment]
The requested change (return empty product instead of CODA error when retrieving a band that is not present in the product) has been implemented. Also, the ingestion has been tested with L1B products up to 2014.
