### ISSUE TITLE
Add support for QA4ECV products

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#89]
Add support for the [NO2](http://www.qa4ecv.eu/ecv/no2-pre), [HCHO](http://www.qa4ecv.eu/ecv/hcho-p), and [CO](http://www.qa4ecv.eu/ecv/co) products of QA4ECV.

The format of the NO2 and HCHO products is similar to that of S5P. The new product for CO will be similar to that of the ESA CCI products.

**Comment by StevenCompernolle** [comment]
QA4ECV NO2 and QA4ECV HCHO both have description 'surface pressure' for the variable name 'pressure_bounds', which is not correct.

**Comment by svniemeijer** [comment]
We should also fix mapping. `/PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/averaging_kernels[]` for HCHO should be `/PRODUCT/averaging_kernel[]`.

**Comment by svniemeijer** [comment]
Initial support for NO2 and HCHO products have been added. CO products will not arrive for a while.
Any additions to the NO2/HCHO products or need for implementing CO products will be done using new tickets. For CO this will be once actual sample data + format specifications become available.
