### ISSUE TITLE
Performing filter after derive() operation results in no data

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#93]
This works and returns data as expected:

`harpconvert -a 'scan_direction=="forward";derive(O3_column_number_density {time} [DU])'`

(used on e.g. a GOME Lvl2 product).

But this results in an empty product:

`harpconvert -a 'derive(O3_column_number_density {time} [DU]);scan_direction=="forward"'`

**Comment by ElessarWebb** [comment]
I'm testing this against the lemon branch and the output of the two variations are identical.

**Comment by svniemeijer** [comment]
This issue was resolved by the change to lex/yacc of for parsing the operations expression.
