### ISSUE TITLE
Change regridding such that lower/upper extrapolation grid points are kept

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#95]
Currently, when regridding a vertical profile the target vertical range is clipped to that of the source range. For instance, if the source grid is [0.5, 1.0, 1.5, 2.0], but the target grid is [0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1] then the grid that will actually be stored is [0.6, 0.9, 1.2, 1.5, 1.8, NaN, NaN].

Although this is technically a correct way to do this, it prevents us from later on subtracting the regridded profile from a profile that used the target grid (since we would be subtracting the value at 0.6 from the value at 0.3).

To make this subtraction possible, the regridding should  be changed such that the target grid is always the full specified target grid. Values in profiles outside the source range will then be set to NaN (e.g. [NaN, ***, ***, ***, ***, ***, ***, NaN]).

It will always be possible to get the old behaviour back by performing a valid() operation on the measurement profile (which we remove all levels where the measurement is NaN), but the reverse is not possible.

**Comment by ElessarWebb** [comment]
This is conceptually just undoing #46, no?

**Comment by svniemeijer** [comment]
The implementation has a problem. The target grid variable from dataset B cannot just be copied to the product of dataset A because the time dimension can be different (line 1465).
You have to first create the grid variable using the right dimensions and then only copy the grid for the specific time index.
